### ISSUE TITLE
Inverted IQ setup not used for Downlinks for SX126x

### ISSUE THREAD

**Issue by vanthome** [LoRaWanMiniMouse/Mini-Mouse#11]
Hello, I think there is a major bug in the function ` SX126x::SetPacketParamsLora( uint8_t payloadSize )`. It is used for Tx **and** Rx while for Rx IQ_INVERTED should be used. Can you confirm this? I'm open to create a PR to fix it then if you want.
BG

**Comment by LoRaWanMiniMouse** [comment]
Hello, thomas,
You are right , it has appear since the merge introducing the fsk , i will correct it assap 
Best 
FH

**Comment by vanthome** [comment]
It works
