### ISSUE TITLE
git clone produces empty directory

### ISSUE THREAD

**Issue by nicbkw** [LoRaWanMiniMouse/Mini-Mouse#6]
git clone https://github.com/LoRaWanMiniMouse/Mini-Mouse.git creates a directory empty except for a LICENSE file

**Comment by Oliv4945** [comment]
Hi @nicbkw ,

It is excepted as all current code is in the [dev ](https://github.com/LoRaWanMiniMouse/Mini-Mouse/tree/dev) branch. You can do:
```
git clone https://github.com/LoRaWanMiniMouse/Mini-Mouse.git
cd Mini-Mouse
git fetch
git checkout dev
```

**Comment by nicbkw** [comment]
Thanks!
